export default {
  FLOWCHART: 'FLOWCHART',
  IDENTIFICADOR: 'IDENTIFICADOR',
  LR: 'LR',
  MARKDOWN: 'MARKDOWN',
  QUEBRA_LINHA: 'QUEBRA_LINHA',
  TD: 'TD',
  TEXTO: 'TEXTO',
  NUMERO: 'NUMERO',
  DOIS_PONTOS: 'DOIS_PONTOS',
}